---
title: "Billboards Top 100 Analysis"
output: html_document
date: '2022-06-21'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(billboard)
library(ggthemes)
```

```{r, echo = FALSE}
x <- wiki_hot_100s |>
  as_tibble() |>
  mutate(year = as.numeric(year))
```


```{r, echo = FALSE}
x|>
  group_by(year)|>
  distinct(artist)|>
  summarize(uniq = n())|>
  ggplot(mapping = aes(x = year, y = uniq, color = uniq)) +
  scale_color_gradient(low = "red", high = "blue")+
  geom_point() +
  geom_smooth(method = "lm", formula = y ~ x, se = FALSE) +
  scale_x_continuous(breaks = seq(1960, 2015, by = 5)) +
  theme_tufte() +
  labs(title = "Uniqueness of artists from the Billboard Top 100",
       subtitle = "The number of distinct artists appear to be increasing over time",
       x = "Year",
       y = "Number of Unique Artists",
       caption = "Data from Wikipedia") +
  theme(plot.title = element_text(face = "bold"),
        panel.background = element_rect(fill = "lightblue"),
        panel.grid.minor.x = element_blank(),
        legend.position = "none")   
```

